// <auto-generated />
using Hive_IT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Hive_IT.Migrations.CustomerData
{
    [DbContext(typeof(CustomerDataContext))]
    [Migration("20171113223346_AlteredColumnNames")]
    partial class AlteredColumnNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hive_IT.Data.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Hive_IT.Data.CustomerAddress", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<long>("CustomerId");

                    b.Property<string>("Postal")
                        .HasMaxLength(6);

                    b.Property<string>("ProvState");

                    b.Property<string>("StreetAddress");

                    b.HasKey("AddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("MailingAddresses");
                });

            modelBuilder.Entity("Hive_IT.Data.CustomerEmail", b =>
                {
                    b.Property<long>("EmailId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CustomerId");

                    b.Property<string>("Email");

                    b.HasKey("EmailId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Hive_IT.Data.CustomerPhoneNumber", b =>
                {
                    b.Property<long>("PhoneId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CustomerId");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13);

                    b.HasKey("PhoneId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("Hive_IT.Data.CustomerAddress", b =>
                {
                    b.HasOne("Hive_IT.Data.Customer", "Customer")
                        .WithMany("CustomerAddress")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hive_IT.Data.CustomerEmail", b =>
                {
                    b.HasOne("Hive_IT.Data.Customer", "Customer")
                        .WithMany("CustomerEmail")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hive_IT.Data.CustomerPhoneNumber", b =>
                {
                    b.HasOne("Hive_IT.Data.Customer", "Customer")
                        .WithMany("CustomerPhoneNumber")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
